name: Documentation

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write

    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'
    - uses: julia-actions/cache@v1
    - name: Install dependencies
      run: |
        julia --project=docs -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate()'
    - name: Build and deploy documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      run: |
        julia --project=docs -e '
          using Pkg;
          Pkg.instantiate();
          include("docs/make.jl")' 