name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'
    - uses: julia-actions/cache@v1
    - name: Install dependencies
      run: |
        julia --project=docs -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate()'
    - name: Build documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: julia --project=docs docs/make.jl
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build
        force_orphan: true
        commit_message: "Deploy documentation"
        destination_dir: .
        keep_files: false 